name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - "iptables-viz/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Backend Build and Push
      - name: Build and Push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./iptables-viz/backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iptables-viz-backend:latest

      # Frontend Build and Push
      - name: Build and Push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./iptables-viz/frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iptables-viz-frontend:latest

  jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: AWS ECR
      uses: kciter/aws-ecr-action@v1
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: # fill this in
        region: us-east-1  # change as needed
        tags: ${{ github.sha }}
        create_repo: true

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v2

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # change as needed

      - name: helm deploy
        uses: koslibpro/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh

      # Backend Deployment
      - name: Deploy Backend using Helm
        run: |
          helm upgrade --install iptables-viz-backend ./iptables-viz \
            --set backend.image.repository=${{ secrets.DOCKERHUB_USERNAME }}/iptables-viz-backend \
            --set backend.image.tag=latest

      # Frontend Deployment
      - name: Deploy Frontend using Helm
        run: |
          helm upgrade --install iptables-viz-frontend ./iptables-viz \
            --set frontend.image.repository=${{ secrets.DOCKERHUB_USERNAME }}/iptables-viz-frontend \
            --set frontend.image.tag=latest
