name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - "iptables-viz/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Backend Build and Push
      - name: Build and Push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./iptables-viz/backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iptables-viz-backend:latest

      # Frontend Build and Push
      - name: Build and Push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./iptables-viz/frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iptables-viz-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install Helm
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh

      # Backend Deployment
      - name: Deploy Backend using Helm
        run: |
          helm upgrade --install iptables-viz-backend ./iptables-viz \
            --set backend.image.repository=${{ secrets.DOCKERHUB_USERNAME }}/iptables-viz-backend \
            --set backend.image.tag=latest
            

      # Frontend Deployment
      - name: Deploy Frontend using Helm
        run: |
          helm upgrade --install iptables-viz-frontend ./iptables-viz \
            --set frontend.image.repository=${{ secrets.DOCKERHUB_USERNAME }}/iptables-viz-frontend \
            --set frontend.image.tag=latest
