name: Build and Deploy
 deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install Helm
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh

      # Backend Deployment
      - name: Deploy Backend using Helm
        run: |
          helm upgrade --install iptables-viz-backend ./iptables-viz/backend \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/iptables-viz-backend \
            --set image.tag=latest

      # Frontend Deployment
      - name: Deploy Frontend using Helm
        run: |
          helm upgrade --install iptables-viz-frontend ./iptables-viz/frontend \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/iptables-viz-frontend \
            --set image.tag=latest
